name: BasicCodePM4
main: Walnut\PluginCode\Main
author: WalnutDEVF
api: 4.0.0
version: 1.0

commands:
   test:
    description: "A basic command pm4"
    permission: test.basic.cmd

permissions:
   test.basic.cmd:
    description: "A permission basic code pm4"
    default: true